To define the name of VPC,number of subnets

#varaibles for VPC
	vpc_name: WORDPRESS
	vpc_region: ap-south-1
	vpc_cidr_block: 172.25.0.0/16
	public_cidr_1: 172.25.10.0/24
	public_az_1: "{{vpc_region}}a"
	public_cidr_2: 172.25.20.0/24
	public_az_2: "{{vpc_region}}b"
	private_cidr: 172.25.30.0/24
	private_az: "{{vpc_region}}c"

	#subnet definition for VPC
		vpc_subnets:
			-cidr: "{{public_cidr_1}}" #public subnet 1
			 az: "{{public_az_1}}"
		resource_tags:{"Name: "{{vpc_name}}-{{public_az_1}}-public-subnet"}
			-cidr: "{{public_cidr_2}}" #public subnet 2
			 az: "{{public_az_2}}"
		resource_tags:{"Name: "{{vpc_name}}-{{public_az_2}}-public-subnet"}
		-cidr: "{{private_cidr}}" #private subnet
			 az: "{{private_az}}"
		resource_tags:{"Name: "{{vpc_name}}-{{private_az}}-private-subnet"}

	#routetable for subnet inside the VPC
    # routing table for public subnet

		public_subnet_rt: 
				-subnets:
				  - "{{public_cidr_1}}"
					- "{{public_cidr_2}}"
				routes: 
					-dest: 0.0.0.0/0
						gw: igw		
		
		
	